### ISSUE TITLE
Pseudomoment Matrix from FindBound

### ISSUE THREAD

**Issue by jindavid** [oxfordcontrol/SOSTOOLS#12]
We are wondering we can obtain the `pseudomoment` matrix from `findbound` like `sossolve`.

For our setting, `findbound` is working but `sossolve` is not due to precision issues.

Thank you for your time and help!

**Comment by djagt** [comment]
Hey,

I'm afraid I don't fully understand your question. Is something not working properly with ```sossolve``` or ```findbound```? 
Please elaborate, and I am happy to help any way I can!

Declan

**Comment by jindavid** [comment]
Hi Declan,

Thank you for your reply!

What I am trying to do is to use `sossolve` to find pseudo-expectation given a polynomial and several constraints. However, it is returning warnings like 

> In psdinvscale (line 73)
> In maxstep (line 63)
> In wregion (line 138)
> In sedumi (line 471)
> In sossolve (line 244)
> In exp2_ld_regression (line 59)
>  
> Warning: Matrix is singular to working precision. 

and  intermediate results like 

> 8 :        NaN      NaN   NaN    NaN 0.0000 0.0000    NaN  1  1  NaN.

Then, instead of using 'sossolve' to solve for the SOSs, we rephrase the constraints and use 'findbound'. However, unlike 'sosolve', 'findbound' would not return a positive-semidefinite matrix that can tell us about the pseudoexpection given the polynomail.

May I ask if you have any suggestions on solving this problem? Thank you again for your help!

David

**Comment by djagt** [comment]
Thank you for clarifying. Quite annoying that your manual approaching is running into numerical problems, I wonder what ```findbound``` does differently that it doesn't encounter such issues...

So, as you know, findbound looks for a greatest lower bound _gam_ on _f(x)_ on the domain defined by _g(x)>=0_ and _h(x)==0_, by solving the SOSP with constraint

_(f-gam) - s(x)*g(x) - p(x)*h(x) = F(x) = SOS polynomial_,

where _s_ and _F_ are SOS variables, and _p_ is just a polynomial variable.
If I understand correctly, you want to know the value of the SDP matrix _Q_ such that _F(x) = Z(x)' * Q * Z(x)_ in this SOS constraint?

Unfortunately, ```findbound``` does not return the solved program structure, so that doesn't give you a lot of information. However, it is easy to add this solved program structure as an output to the function. In this program structure, the SOS variable _F_ will be represented through the field "extravar", added only to represent the right-hand side of the SOS constraint. The solved SDP matrix, in this case, can be found under ```prog.solinfo.extravar.primal{1}```, where ```prog``` is the solved program structure.

I attached a slightly adjusted ```findbound_adjst``` function, which returns as fourth output the solved program structure, and as sixth output the solved SDP matrix _Q_ representing the variable _F(x)_ in the right-hand side of the SOS constraint:

[findbound_adjst_txt.txt](https://github.com/oxfordcontrol/SOSTOOLS/files/10282798/findbound_adjst_txt.txt)

Is this the matrix that you are after? Let me know if this doesn't answer your question.

Declan

**Comment by jindavid** [comment]
Thank you so much for your help! I think this might be what we need. Let me go try this out!

Best,
David

**Comment by djagt** [comment]
Hey David, just to let you know, I will be closing this issue. Feel free to reopen the issue, or open a new one if you encounter any other problem.

Declan
