### ISSUE TITLE
An instance of parameterized problems?

### ISSUE THREAD

**Issue by PoeticExposition** [oxfordcontrol/SOSTOOLS#15]
Currently, I cannot find an example of this topic in the documentation, but I find an example here: [Example 2: Parametric SOS problems](https://sums-of-squares.github.io/sos/#example-2-parametric-sos-problems). 
However, when I execute the given code in MatLab: 
```MatLab
>> syms x y s t
p = s*x^6 + t*y^6 - x^4*y^2 - x^2*y^4 - x^4 + 3*x^2*y^2 - y^4 - x^2 - y^2 + 1;

prog = sosprogram([x;y], [s;t]);
prog = sosineq(prog, p);     % ERROR
```
I just get an error: 
```
Unable to perform assignment because value of type 'sym' is not convertible to 'double'.
Error in getequation (line 289)
                    coeffnts((ind_k-1)*dimp+i,j) = s_ijk;
Error in sosconstr (line 104)
        getequation(char(symexpr),sos.vartable,sos.decvartable,sos.varmat.vartable);
Error in sosineq (line 125)
sos = sosconstr(sos,'ineq',symexpr);
Caused by:
    Error using symengine
    Unable to convert expression containing symbolic variables into double array. Apply 'subs' function
    first to substitute values for variables. 
```
I find that if I use `pvar` (instead of `syms`), these messages will disappear. Is this a bug? 

(By the way, YALMIP's help page does give a "parametric" example. Maybe SoSTools's documentation can add such an example later.)

**Comment by djagt** [comment]
Hey,

What you pointed out is definitely a bug. The issue here is that the decision variables in `sosprogram` in the `syms` case needed to be specified as row vector rather than as column vector. Otherwise, this would yield problems later on, like the one you encountered.
However, we recently pushed a fix, that allows the decision variables to be specified as column vector as well. If you pull the latest version of the codes from GitHub, this should resolve the issue. That being said, I do recommend the use of the `pvar`/`dpvar` implementation in general.

Also, thanks for pointing out this lack of parametric examples. I agree, it would be useful to include such an example in the manual/demos as well.

Let me know if this doesn't resolve your issue, or if you encounter another one.

**Comment by PoeticExposition** [comment]
Thanks. It appears that the results are not so accurate. (But I'm not sure if the numerical solution is feasible mathematically.) 
Incidentally, though the above website contains five examples, only the first four examples have MatLab codes. It seems that SosTools cannot tackle the fifth example (i.e., [Dual formulation and Pseudoexpectations](https://sums-of-squares.github.io/sos/#example-5-dual-formulation-and-pseudoexpectations)) as yet. Am I right?

**Comment by djagt** [comment]
I'm not sure what you mean with the accuracy of the result. Are you referring to the obtained values for the decision variables s and t?
And indeed, SOSTOOLS has no functions to e.g. declare a pseudo-expectation operator. Perhaps it is possible to declare a problem such as the fifth example in SOSTOOLS, but I'm unaware of a methodology for doing so.

**Comment by PoeticExposition** [comment]
Thank you! 
Edit. I have erased the previous reply, since I made a mistake (Sorry for it.) before.

**Comment by PoeticExposition** [comment]
> Also, thanks for pointing out this lack of parametric examples. I agree, it would be useful to include such an example in the manual/demos as well. 

Sorry for re-activating this issue. 
The objective function (namely, the second argument of `sossetobj`) seems to be only allowed to be linear at present, but I notice that certain novel solvers is capable of solving SDPs with bilinear matrix inequalities, so I'm wondering, could the objective be extended to be quadratic in future releases? 
Besides, can I declare that the parametric variables (i.e., the second argument of `sosdecvar`) should only take integer values? (The answer appears to be "no", as currently supported solvers do not solve mixed-integer SDPs, yet are there any plans to add support for integer-valued decision variables (just like YALMIP)?)

**Comment by djagt** [comment]
Indeed, at this time, only linear objective functions can be declared, and we cannot enforce decision variables to be integer. Although, at this time, there are no explicit plans to include such features, they are certainly good suggestions for updates, and ones that we may work on at some point. If the solvers already allow for nonlinear objective functions, we should be able to allow for such functions to be specified as well, but I do not know if and when we may incorporate such a feature. Nevertheless, I do appreciate the suggestions, and I will certainly be looking into them.

**Comment by PoeticExposition** [comment]
Thanks. A disadvantage is that the SeDuMi format (used by default in SOSTOOLS's `sossolve`) does not support quadratic objectives (and sundry novel solvers, regretfully, do not accept the SeDuMi format). 
 Besides, I read that the Remark 6.2 of [this paper](https://wangjie212.github.io/jiewang/research/sparsesos.pdf#page=6) claimed that “when we use the 'sparse' option, SOSTOOLS seems to make a mistake in computing a monomial basis” (and the Remark 6.1 of the same paper suggested that SOSTOOLS lacks certain further pre-processings[/](https://yalmip.github.io/example/moresos/)post-processings like YALMIP). Has this bug been fixed?

**Comment by djagt** [comment]
Sorry for the late response. Indeed, SOSTOOLS relies on the SeDuMi format to pose the SOS program as an SDP, and conversion to different solver formats is only performed when calling ``sossolve``. We'll have to see how we could adjust this to potentially incorporate quadratic objectives.
Regarding that Remark 6.2, I ran the example, and SOSTOOLS seems to be able to certify nonnegativity of the polynomial, both with and without 'sparse' option. Whatever the bug was, I suppose it has been fixed, but I'll take a closer look at it to be sure. Thanks for pointing that out!
