### ISSUE TITLE
More about `findbound`

### ISSUE THREAD

**Issue by PoeticExposition** [oxfordcontrol/SOSTOOLS#22]
As the documentation says, `[GAM, VARS, XOPT] = findbound(P, INEQ, EQ, DEG, OPTIONS)` will compute the largest GAM such that “(P－GAM)－LAM'×EQ－SIGMA1'×INEQ－…” is a sum of squares, but it appears that `findbound` does not return `LAM` and `SIGMA`. How can I get the two vectors from the output?

**Comment by djagt** [comment]
Hi, I'm afraid the outputs of `findbound` don't really allow you to reconstruct the functions LAMBDA and SIGMA representing the multipliers for enforcing the equality and inequality constraints. However, it is not very difficult to adjust the function to output those multipliers as well. I have attached an example of such a version, returning the multipliers as `SIG` and `LAM`. Do keep in mind that `findbound` also uses the given inequality constraints to construct additional valid inequality constraints, so that the length of `SIG` may exceed that of the input `INEQ`, but you can just ignore the additional elements if you like. Let me know if there are any problems downloading or running the function, or if you have any questions.

[findbound_adjst_SIG_LAM.zip](https://github.com/user-attachments/files/17535985/findbound_adjst_SIG_LAM.zip)

**Comment by PoeticExposition** [comment]
Many thanks. This is useful! Yet I have an additional question: 
Sometimes the last output `XOPT` is a vector of `NaN` (or just an empty vector); did I miss something? 
```MatLab
syms q s r
[~,~,opts]=findbound(((1^2-9*q)*(1^4+q^2)+(43/2)*(1*q)^2)+...
1*(26*1^2-113*q)*r+(387/2)*r^2-(3*1*(1^2-(9/2)*q)+(121/2)*r)*s,...
[q;r],[q^2*(1^2-4*q)-2*1*r*(2*1^2-9*q)-27*r^2-s^2],4,...
struct('frlib',struct('approx','dd','removeDualEq',1,'useQR',1)));
```
```
>> opts
opts =
   NaN
   NaN
   NaN
```

**Comment by djagt** [comment]
So `findbound` may not always be able to find an actual value x for which f(x)==gam is satisfied. Indeed, `findbound` only finds gam for which f(x)-gam==s(x) is satisfied for some SOS function s(x), and although in some cases the solution to the dual problem actually offers a point x for which f(x)=gam, this may not be true in general, in which case `xopt==[]` is returned. 
I am not sure why you are getting `xopt=NaN`, though. I suspect the optimization problem may not have been solved at all, but I was unable to replicate your result, as `frlib` returns an error when I try to run this code. If I run without using `frlib`, I get `xopt=[]`.

**Comment by PoeticExposition** [comment]
Thanks for the explanation.  Recently, I found that when using SDPT3, the following code causes an exception: 
```MatLab
pvar s q r
findbound(((1^2-9*q)*(1^4+q^2)+(43/2)*(1*q)^2)+1*(26*1^2-113*q)*r+(387/2)*r^2-...
(3*1*(1^2-(9/2)*q)+(121/2)*r)*s,[q;r],[q^2*(1^2-4*q)-2*1*r*(2*1^2-9*q)-27*r^2-...
s^2],12,struct('solver','sdpt3','params',struct('printlevel',0),'simplify',true));
```
If I switch to another solver, the error will disappear. Besides, if I use `syms` instead, MatLab will hang. Are these two bugs in SOSTOOLS?

**Comment by djagt** [comment]
I think there may be a bug in the post-processing of the SDPT3 solution. In particular, in `sossolve` line 378, I believe `smblkdim` should be assigned the same value as `smallblkdim` in line 363 (I am not sure why these are currently given separate names and values). If I set `smblkdim=smallblkdim`, I can run your code without getting an error. Does this change solve your error as well?

And in general, the 'pvar'/'dpvar' implementation is numerically a lot cheaper than the 'syms' implementation, both in terms of computation time and memory. Since you are requesting to use polynomials of degree 12 (in three variables), the 'syms' implementation in this case will take a lot of time to run. I would recommend using 'pvar'/'dpvar' in general, and try starting with lower degrees (e.g. degree 4 instead of 12) to reduce computation time as well as numerical errors.

**Comment by PoeticExposition** [comment]
Thank you! These resolved the issues.
